# .github/workflows/cd.yml
name: Release CD

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download built artifact
      uses: actions/download-artifact@v2
      with:
        name: arkade-lvlup

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: New release for ${{ github.ref_name }}
          token: ${{ secrets.MY_PAT }}
          draft: false
          prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./arkade-lvlup
        asset_name: arkade-lvlup-${{ runner.os }}
        asset_content_type: application/octet-stream
