# .github/workflows/cd.yml
name: Release CD

on:
    workflow_run:
      workflows: ["Go Build and Test CI"]
      types:
        - completed

jobs:
  release:
    name: Create Release and Upload Assets
    runs-on: ubuntu-latest
    steps:
    - name: Check CI success
      run: |
        if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
          echo "CI did not complete successfully. Aborting CD."
          exit 1
        fi

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download all built artifacts
      uses: actions/download-artifact@v2
      with:
        path: ./artifacts

    - name: Rename Apple Silicon binary
      run: |
        if [ -f "./artifacts/arkade-lvlup-macos-latest-arm64" ]; then
            mv ./artifacts/arkade-lvlup-macos-latest-arm64 ./artifacts/arkade-lvlup-macos-latest-applesilicon
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      with:
          tag_name: ${{ github.event.workflow_run.head_commit.ref }}
          release_name: Release ${{ github.event.workflow_run.head_commit.ref }}
          body: New release for ${{ github.event.workflow_run.head_commit.ref }}
          token: ${{ secrets.MY_PAT }}
          draft: false
          prerelease: false

    - name: Upload Release Assets
      run: |
        for file in ./artifacts/*; do
          if [[ -f "$file" ]]; then
            echo "Uploading $file..."
            curl \
              -H "Authorization: token ${{ secrets.MY_PAT }}" \
              -H "Content-Type: $(file -b --mime-type $file)" \
              --data-binary @"$file" \
              "${{ steps.create_release.outputs.upload_url }}?name=$(basename $file)"
          fi
        done

    # Check if it should release, based on the tag or [FORCE RELEASE] message.
    if: "startsWith(github.event.workflow_run.head_commit.ref, 'refs/tags/') || contains(github.event.workflow_run.head_commit.message, '[FORCE RELEASE]')"
