# .github/workflows/ci.yml
name: Go Build and Test CI

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        goarch: [amd64, arm64]
    runs-on: ${{ matrix.os }}
    if: "github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || contains(github.event.head_commit.message, '[FORCE BUILD]')"
    env:
      GOARCH: ${{ matrix.goarch }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Test
      run: go test ./...

    - name: Build binary
      run: go build -o arkade-lvlup-${{ matrix.os }}-${{ matrix.goarch }} .

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: arkade-lvlup-${{ matrix.os }}-${{ matrix.goarch }}
        path: ./arkade-lvlup-${{ matrix.os }}-${{ matrix.goarch }}

    - name: Rename Apple Silicon binary
      if: runner.os == 'macOS' && matrix.goarch == 'arm64'
      run: mv arkade-lvlup-macos-latest-arm64 arkade-lvlup-macos-latest-applesilicon
